### ISSUE TITLE
Selecting one of suggested traits after "is" adds closing "]"

### ISSUE THREAD

**Issue by jisoldi** [mulesoft-labs/raml-suggestions#23]
When a trait suggestion after a 'is' selected the closing ']' is added but there ir no opening '['

With this example:
```
#%RAML 1.0
title: testConsumeFragment
traits: 
 secured: !include /exchange_modules/mulesoft-720/e2etrait_j3aczpxg882/1.0.0/trait.raml
/testResource:
  is: s
```

If you suggest after the last char, and select the 'secured' option, the text to insert is 'secured]', which results in this:
```
#%RAML 1.0
title: testConsumeFragment
traits: 
 secured: !include /exchange_modules/mulesoft-720/e2etrait_j3aczpxg882/1.0.0/trait.raml

/testResource:
  is: secured]
```

**Comment by dreamflyer** [comment]
@javok002, can not to reproduce, please provide more info, including at least your OS version and contents of '/exchange_modules/mulesoft-720/e2etrait_j3aczpxg882/1.0.0/trait.raml' file.

**Comment by leckoluck** [comment]
@dreamflyer I think that the problem is that the suggest after "is" is suggesting "secured" and it leaves an file with an error, because "is" expect to be an array:

```
#%RAML 1.0
title: testConsumeFragment
traits: 
 secured: !include /exchange_modules/mulesoft-720/e2etrait_j3aczpxg882/1.0.0/trait.raml

/testResource:
  is:
```
```
#%RAML 1.0
title: testConsumeFragment
traits: 
 secured: !include /exchange_modules/mulesoft-720/e2etrait_j3aczpxg882/1.0.0/trait.raml

/testResource:
  is: secured
```

It should suggest:
```
#%RAML 1.0
title: testConsumeFragment
traits: 
 secured: !include /exchange_modules/mulesoft-720/e2etrait_j3aczpxg882/1.0.0/trait.raml

/testResource:
  is: [secured]
```

It works fine, if you have something like
`is: [`

the content of the trait is:
```
#%RAML 1.0 Trait
usage: Apply this to any method that needs to be secured
description: Some requests require authentication.

headers:
  access_token:
    displayName: token
    description: Access token
    example: "10"
    required: true
protocols: HTTP
queryParameters:
  name: string
responses:
  200:
    body:
      application/json:
        type: string
        examples:
          example1: SSSL
          example2: 1AA
```
