### ISSUE TITLE
No enum completion for samples

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft-labs/raml-suggestions#6]
RAML:

```
#%RAML 1.0 Api

types:
  TestEnum:
    type: string
    enum: [one, two]
    example: one
```

There is no completion for `one` value in `example: one`

Same for 

```
types:
  TestEnum:
    type: string
    enum: [one, two]
    example: one
  TestType2:
    properties: 
      prop: TestEnum
    example: 
      prop: one
```

`prop: one`
