### ISSUE TITLE
No enum completion for annotation instances

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft-labs/raml-suggestions#7]
```
#%RAML 1.0 Library

types:
  TestEnum:
    type: string
    enum: [one, two]
    example: one

annotationTypes:
  TestAnnotation: TestEnum

resourceTypes:
  AnnotatedResource:
    (TestAnnotation): one
```

There is no completion for `one` value in `(TestAnnotation): one`
